# Generated by Django 5.1.3 on 2024-11-12 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='users.user'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('course', 'student', 'date')},
        ),
    ]
